### PR TITLE
Wallet: Token Name Display styling in header

### PR DESCRIPTION
**Pull request by vsashyn**

### CODE REVIEW

**Comment by wolverineks** [comment]
Please add similar styling to the exchange screen

https://github.com/Airbitz/edge-react-gui/blob/fe4e503bdd2ed16d86336fb80c5b4505bd973039/src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js#L82

**Comment by paullinator** [comment]
Sorry, it looks like this got refactored after your PR and this now needs to deal with some hefty merge conflicts. Please resubmit with conflicts fixed.

**Comment by kylanhurt** [comment]
@paullinator Should we close this PR?

**Comment by vsashyn** [comment]
I merged with new develop and added styles to `CryptoExchangeFlipInputWrapperComponent.js`

**Pull request merged**
