### PR TITLE
Add settings lock

### PR DESCRIPTION
**Pull request by ahujsak**
• new button to lock and unlock settings
• new dialog box to confirm password
• new Icons for locked and unlocked
• removed dead code

### CODE REVIEW

**Comment by paullinator** [comment]
Please do not merge this request until iOS/Android releases for this week are out the door

**Comment by wolverineks** [comment]
Please flow any files that you edited that aren't already flowed, if possible

**Comment by ahujsak** [comment]
@wolverineks the changes were made with flow, can you please re-review.

**Comment by ahujsak** [comment]
This @swansontec typing on Allen's computer. Everything seems pretty legit in this PR. Will approve.

**Pull request merged**
