### PR TITLE
Paul/add ripple monero qtum ufo

### PR DESCRIPTION
**Pull request by paullinator**
Add Ripple, Monero, Qtum, and Ufo blockchain support

### CODE REVIEW

**Comment by wolverineks** [comment]
What are postinstall.sh and postinstall.js?

**Comment by wolverineks** [comment]
Why did you update edge-core-js?

**Comment by wolverineks** [comment]
What do these do?
`"https-proxy-agent": false,`
`"tls": "react-native-tcp/tls`

**Comment by paullinator** [comment]
Updated to use npm published modules vs git modules. Ripple lib was using 3 layers deep of git dependencies and I figured it might be causing the problem. 

Travis now passes Android build and iOS gets much further and stalls in the Xcode portion of the build which is an issue we’ve sporadically seen. Given Allen’s approval, I’m merging this now.

**Pull request merged**
