### PR TITLE
Add seconds/minutes/hours for selecting time in AutoLogoutModal

### PR DESCRIPTION
**Pull request by vsashyn**

### CODE REVIEW

**Comment by wolverineks** [comment]
@vsashyn Right now the autologout settings row displays the duration in minutes.
Instead of just the minutes, could you display what the user selected: e.g `1 day(s)` instead of `1440`

**Comment by vsashyn** [comment]
Hi @wolverineks! Added displaying with measurements. Thanks.

**Comment by ahujsak** [comment]
@vsashyn there are conflicts with this that need to be resolved before merging. Can you fix and re-submit.

**Comment by vsashyn** [comment]
Hi @ahujsak. Conflicts are resolved.

**Pull request merged**
